services:
  - type: web
    name: scraper-project
    env: python
    buildCommand: |
      pip install -r requirements.txt
      bash build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
